import React, { useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { Filter, RefreshCcw, ChevronLeft, ChevronRight, Printer } from "lucide-react";

interface Patient {
  id: string;
  name: string;
  examination: string;
  commission: number;
  transferDate: Date;
  selected?: boolean;
}

const demoData: Patient[] = [
  {
    id: "P001",
    name: "John Smith",
    examination: "MRI Scan",
    commission: 150.0,
    transferDate: new Date("2024-03-15"),
  },
  {
    id: "P002",
    name: "Sarah Johnson",
    examination: "Blood Test",
    commission: 75.5,
    transferDate: new Date("2024-03-14"),
  },
  {
    id: "P003",
    name: "Michael Brown",
    examination: "X-Ray",
    commission: 95.0,
    transferDate: new Date("2024-03-13"),
  },
  {
    id: "P004",
    name: "Emily Davis",
    examination: "CT Scan",
    commission: 200.0,
    transferDate: new Date("2024-03-12"),
  },
  {
    id: "P005",
    name: "Robert Wilson",
    examination: "Ultrasound",
    commission: 120.0,
    transferDate: new Date("2024-03-11"),
  },
].map(patient => ({ ...patient, selected: false }));

const PatientsView: React.FC = () => {
  const [startDate, setStartDate] = useState<Date | null>(null);
  const [endDate, setEndDate] = useState<Date | null>(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [patients, setPatients] = useState(demoData);
  const [selectAll, setSelectAll] = useState(false);
  const itemsPerPage = 5;

  const formatDate = (date: Date) => {
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
    }).format(amount);
  };

  const totalCommissions = patients.reduce(
    (sum, patient) => sum + patient.commission,
    0
  );
  const totalPages = Math.ceil(patients.length / itemsPerPage);

  const handleReset = () => {
    setStartDate(null);
    setEndDate(null);
  };

  const handleSelectAll = () => {
    setSelectAll(!selectAll);
    setPatients(patients.map(patient => ({ ...patient, selected: !selectAll })));
  };

  const handleSelectPatient = (id: string) => {
    setPatients(patients.map(patient => 
      patient.id === id ? { ...patient, selected: !patient.selected } : patient
    ));
  };

  const handlePrint = () => {
    const selectedPatients = patients.filter(patient => patient.selected);
    if (selectedPatients.length === 0) {
      alert("Please select at least one patient to print");
      return;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Patient Report</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; }
            .logo { font-size: 24px; font-weight: bold; color: #1a56db; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #f8fafc; }
            .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
            .total { margin-top: 20px; text-align: right; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">Medical Center</div>
            <p>Patient Report - ${new Date().toLocaleDateString()}</p>
          </div>
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Patient Name</th>
                <th>Examination</th>
                <th>Commission</th>
                <th>Transfer Date</th>
              </tr>
            </thead>
            <tbody>
              ${selectedPatients.map(patient => `
                <tr>
                  <td>${patient.id}</td>
                  <td>${patient.name}</td>
                  <td>${patient.examination}</td>
                  <td>${formatCurrency(patient.commission)}</td>
                  <td>${formatDate(patient.transferDate)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="total">
            Total Commission: ${formatCurrency(selectedPatients.reduce((sum, patient) => sum + patient.commission, 0))}
          </div>
          <div class="footer">
            <p>Generated by Medical Center Management System</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="w-full bg-white rounded-lg shadow-md p-6">
      <div className="text-center mb-4">
        <h2 className="text-2xl font-bold text-gray-800">Registered Patients</h2>
        <div className="w-24 h-1 bg-blue-500 mx-auto mt-2 rounded-full"></div>
      </div>

      <div className="flex flex-wrap items-end justify-between gap-4 mb-6">
        <div className="flex flex-wrap gap-4">
          <div className="flex flex-col">
            <label className="text-sm font-bold text-gray-800 mb-1">
              Start Date
            </label>
            <DatePicker
              selected={startDate}
              onChange={(date) => setStartDate(date)}
              className="px-3 py-2 border-2 border-black rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholderText="Select start date"
              maxDate={endDate || new Date()}
            />
          </div>
          <div className="flex flex-col">
            <label className="text-sm font-bold text-gray-800 mb-1">
              End Date
            </label>
            <DatePicker
              selected={endDate}
              onChange={(date) => setEndDate(date)}
              className="px-3 py-2 border-2 border-black rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholderText="Select end date"
              minDate={startDate}
              maxDate={new Date()}
            />
          </div>
        </div>

        <div className="flex gap-2">
          <button className="flex items-center px-4 py-2 bg-blue-500 text-white rounded-full hover:bg-blue-600 transition-colors">
            <Filter className="w-4 h-4 mr-2" />
            Filter
          </button>
          <button
            onClick={handleReset}
            className="flex items-center px-4 py-2 border-2 border-black text-black rounded-full hover:bg-gray-100 transition-colors"
          >
            <RefreshCcw className="w-4 h-4 mr-2" />
            Reset
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center px-4 py-2 bg-green-500 text-white rounded-full hover:bg-green-600 transition-colors"
          >
            <Printer className="w-4 h-4 mr-2" />
            Print Selected
          </button>
        </div>
      </div>

      <div className="mb-4">
        <p className="text-sm text-gray-600">
          Showing {patients.length} of {patients.length} Patients
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[800px]">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                <input
                  type="checkbox"
                  checked={selectAll}
                  onChange={handleSelectAll}
                  className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                ID
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                Patient Name
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                Examination
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                Commission
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">
                Transfer Date
              </th>
            </tr>
          </thead>
          <tbody>
            {patients.map((patient) => (
              <tr
                key={patient.id}
                className="border-b border-gray-100 hover:bg-gray-50"
              >
                <td className="px-4 py-3">
                  <input
                    type="checkbox"
                    checked={patient.selected}
                    onChange={() => handleSelectPatient(patient.id)}
                    className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                  />
                </td>
                <td className="px-4 py-3 text-sm text-gray-600">{patient.id}</td>
                <td className="px-4 py-3 text-sm text-gray-800 font-medium">
                  {patient.name}
                </td>
                <td className="px-4 py-3 text-sm text-gray-600">
                  {patient.examination}
                </td>
                <td className="px-4 py-3 text-sm text-gray-600">
                  {formatCurrency(patient.commission)}
                </td>
                <td className="px-4 py-3 text-sm text-gray-600">
                  {formatDate(patient.transferDate)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-6">
        <div className="flex justify-end mb-2">
          <p className="text-sm text-gray-600">
            Total Commission:{" "}
            <span className="font-semibold">
              {formatCurrency(totalCommissions)}
            </span>
          </p>
        </div>

        <div className="flex items-center justify-center gap-2">
          <button
            onClick={() => setCurrentPage((prev) => Math.max(prev - 1, 1))}
            disabled={currentPage === 1}
            className="p-2 border-2 border-black rounded-full text-black hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <ChevronLeft className="w-5 h-5" />
          </button>

          <span className="px-4 py-2 rounded-lg bg-gray-100">
            Page {currentPage} of {totalPages}
          </span>

          <button
            onClick={() => setCurrentPage((prev) => Math.min(prev + 1, totalPages))}
            disabled={currentPage === totalPages}
            className="p-2 border-2 border-black rounded-full text-black hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default PatientsView;